apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: togglemaster-rules
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    app: kube-prometheus-stack
spec:
  groups:
    - name: togglemaster.rules
      interval: 30s
      rules:
        - alert: HighErrorRate5xx
          expr: |
            (
              sum(rate(http_requests_total{status=~"5..",service="auth-service"}[2m]))
              /
              sum(rate(http_requests_total{service="auth-service"}[2m]))
            ) * 100 > 5
          for: 1m
          labels:
            severity: critical
            service: auth-service
            action: restart
          annotations:
            summary: 'Auth-service com error rate > 5%'
            description: 'auth-service está com {{ $value | printf "%.2f" }}% de erros 5xx nos últimos 2min. Self-healing acionado.'

        - alert: ServiceDown
          expr: up{job=~".*-service"} == 0
          for: 1m
          labels:
            severity: critical
            service: '{{ $labels.job }}'
          annotations:
            summary: 'Service {{ $labels.job }} está down'
            description: '{{ $labels.job }} não responde há 1min'
