apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alert-bridge
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:vitorrgabriell/togglemaster-gitops.git
    targetRevision: main
    path: apps/alert-bridge
    directory:
      include: '{configmap.yaml,deployment.yaml,service.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
