apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: tech-challenge
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: 997920956342.dkr.ecr.us-east-1.amazonaws.com/togglemaster/auth-service:latest
          ports:
            - containerPort: 8001
          envFrom:
            - secretRef:
                name: auth-db-secret
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4318"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "http/protobuf"
            - name: OTEL_SERVICE_NAME
              value: "auth-service"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace=togglemaster,deployment.environment=production"
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
